### PR TITLE
"added binary search program"

### PR DESCRIPTION
**Pull request by yashaggarwal0722**

### CODE REVIEW

**Comment by techschneiderrr** [comment]
Great effort Yash !!

**Comment by yashaggarwal0722** [comment]
Thank you 😀

**Comment by yashaggarwal0722** [comment]
> Great effort Yash !!

can you mark it as hacktoberfest-accepted.

**Comment by yashaggarwal0722** [comment]
please mark it as hacktober fest accepted, else my effort will go in vain.

**Pull request merged**
